name: Matrix demo
on: [ push, pull_request, workflow_dispatch ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:

        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
    - uses: actions/terraform@v1
