name: Matrix demo
on: [ push, pull_request, workflow_dispatch ]
jobs:
  build:
    strategy:
      matrix:

        os: [ ubuntu-latest, windows-latest, macos-latest ]
   
    runs-on: ${{ matrix.os }}
    steps:
          - uses: hashicorp/setup-terraform@v3
